server:
  port: 8083
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=pfe;integratedSecurity=true
    username:
    password:

logging:
  level:
    ma.pfe: ERROR
    org.springframework.web: DEBUG
