server:
  port: 8085


spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=pfe;integratedSecurity=true
    username:
    password:

logging:
  level:
    ma.geo: INFO
